modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "dated_draughts"
version = "${version}"
displayName = "Dated Draughts"
authors = "SSBlur"
description = '''
Get blasted on the past!
'''
#logoFile = ""

[[dependencies.dated_draughts]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dated_draughts]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dated_draughts]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "dated_draughts.mixins.json"
